language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bootmap' ]; then cd .. && eval "mv $currentfolder generator-bootmap" && cd generator-bootmap; fi

